### ISSUE TITLE
Cant compile Dev branch

### ISSUE THREAD

**Issue by jimmyeao** [BlueAndi/esp-rgb-led-matrix#103]
Dev branch seems to have more dependencies which are un resolved, VSCODE throws multiple errors due to missing xtensa/hal.h:

```
#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (E:\GitHub\blueandi\esp-rgb-led-matrix\src\Common\Settings.cpp).C/C++(1696)
cannot open source file "xtensa/hal.h" (dependency of "Preferences.h")C/C++(1696)
```

**Comment by gabryelreyes** [comment]
Please check your VSCode installation as well as your PlatformIO installation.

**Comment by jimmyeao** [comment]
As above, master branch compiles fine, dev branch throws the errors.
All my other projects compile fine too, pretty sure vscode/pio/git are solid

**Comment by BlueAndi** [comment]
Which PIO version do you use?
For which target do you build?

The error sounds like a IDF related problem, which is strange.

**Comment by BlueAndi** [comment]
Maybe a problem with the Arduino package(s) in the .platformio home in your user directory.

**Comment by jimmyeao** [comment]
> 

I've completely reset PIO, and now its compiling. Strange how prod would but dev wouldn't before :/
