### ISSUE TITLE
esp8266 support?

### ISSUE THREAD

**Issue by rumjar86** [BlueAndi/esp-rgb-led-matrix#111]
Hi, I was just hoping you would do some support for esp 8266?

**Comment by BlueAndi** [comment]
Hi, it might be possible to support the esp8266. Currently its not planned as other features have a higher priority. Lets see what 2023 will bring. :-)

**Comment by BlueAndi** [comment]
No freeRTOS suppport: https://github.com/esp8266/Arduino/issues/8403

**Comment by BlueAndi** [comment]
Unfortunately the esp8266 can not be supported without a huge amount of effort. The way points to dual core variants and more flash space, as the number of features grows.
