### ISSUE TITLE
ESP32 resets when connecting to access point

### ISSUE THREAD

**Issue by JoeDante** [BlueAndi/esp-rgb-led-matrix#113]
I built my Pixelix, but as soon as I connect to the access point with my phone, the Pixelix resets and the access point is closed. 
I use a AZ-Delivery V4 ESP32.

What I already tried: Reflashing firmware and file system, tested 2 different power supplies (3A and 4A), checked the cables, checked for shorts and faulty solder, removed the light and temp sensor and checked the correct IO pins. 

I turn on the Pixelix, hold the user button, Pixelix shows the SSID and opens an access point. As soon as I connect to the access point with my phone, Pixelix resets. Every time. 
What could be the reason for that?

**Comment by BlueAndi** [comment]
Can you attach the log output (via serial connection)? And did you try a different device than your phone?
Did you use the master branch (tag)  or the Development branch?
