### ISSUE TITLE
WiFi password for first boot

### ISSUE THREAD

**Issue by rumjar86** [BlueAndi/esp-rgb-led-matrix#116]
I know I'm Probably a real dill but I am having issues with the default password on first boot. I have tried the Luke, I am your father but all variations but am not having any luck. please any help would be greatly appreciated.

**Comment by BlueAndi** [comment]
No problem, its not in the README on the master branch. But with the next release, it will be there as well.
You can find it in the Development branch README: https://github.com/BlueAndi/esp-rgb-led-matrix/tree/Development#very-first-startup
