### ISSUE TITLE
[Issue] Open Weather Issue

### ISSUE THREAD

**Issue by lilxanman** [BlueAndi/esp-rgb-led-matrix#138]
I have a ESP32 running the ESP32-doit-devkit version 7.0.0b

After installing the OpenWeather Plugin, and inputing a API key, it only shows a ?. 

Note: I tried upgrading to the newer version v7.1 but I couldn't get it to work.

**Comment by lilxanman** [comment]
This issue somehow fixed itself

**Comment by BlueAndi** [comment]
:-)
