### ISSUE TITLE
[Bug] Countdown Plugin Restart Issues

### ISSUE THREAD

**Issue by lilxanman** [BlueAndi/esp-rgb-led-matrix#142]
**Describe the bug**

When you save the date on the countdown plugin, the correct information shows on the matrix, when the esp32 repowers, the countdown plugin will display a "?". I've found that when I go into the web panel, that the information I entered is there.

Note: When I click the update button, the date shows again until it reboots.

**To Reproduce**
1. Go to Plugins > CountdownPlugin
2. Enter in details
3. Click Update
4. Restart The Device

**Expected behavior**
The correct countdown information should show upon reboot

**Please complete the following information:**
 - Development board: esp32doit-devkit-v1
 - Version: v7.1.1:lc

**Additional context**

**Log**
If applicable, add serial log output to support the analysis.

**Comment by BlueAndi** [comment]
I can not reproduce it with the official release v7.1.1, but in the Development branch. You wrote v7.1.1:lc, which means official release with local changes. Do you use the main or the development branch?

The "?" will stay in case the time was not synchronized by the NTP.

**Comment by BlueAndi** [comment]
I fixed the problem in the Development branch. Please verify and if the problem still exists, reopen the issue.
