### ISSUE TITLE
nothing happened after update

### ISSUE THREAD

**Issue by hznupeter** [BlueAndi/esp-rgb-led-matrix#145]
I have updated software follow the steps below
[Use Espressif Flash Download Tool ](https://github.com/BlueAndi/esp-rgb-led-matrix/blob/master/doc/config/SW-UPDATE.md#use-espressif-flash-download-tool-windows-only)
everything is ok,after finished, nothing happend,i cant scan the WIFI named pixelix.

**Comment by BlueAndi** [comment]
Can you provide some more informations? Which board do you have? Which binaries did you choose? Is there any log message on the serial console?

**Comment by BlueAndi** [comment]
@hznupeter ?
