### ISSUE TITLE
[Feature] Add rotate display 180deg for T-Display-S3

### ISSUE THREAD

**Issue by P1X3L8** [BlueAndi/esp-rgb-led-matrix#148]
I didn't see any easy way of doing this in the code. TY

**Comment by nhjschulz** [comment]
Is it is only for the display on the T-Display-S3 and you don't need dynamic configuration through the UI ?  Then this single line change should do the trick:

Add the line "m_tft.setRotation(2);" into  file lib\HalTftDisplay\src\Display.h, function begin() as shown below.
```
/**
     * Initialize base driver for the display.
     *
     * @return If successful, returns true otherwise false.
     */
    bool begin() final
    {
        m_tft.init();
        m_tft.setRotation(2);
        m_tft.fillScreen(TFT_BLACK);

        return true;
    }
```

**Comment by P1X3L8** [comment]
Hi nhjschulz, this worked, thank you!

**Comment by BlueAndi** [comment]
Thanks nhjschulz for providing this feature.
