### ISSUE TITLE
JustText Plugin does not update the text from the web page

### ISSUE THREAD

**Issue by PabluskiNC** [BlueAndi/esp-rgb-led-matrix#15]
Found that the update button on the JustText plugin page fails to update the text. The API works fine.
Also found that the issue is in the JusttextPlugin.html file - line 136:

Fails:
javascript:setText(pluginUid.options[pluginUid.selectedIndex].value

Works:
javascript:setText(pluginUidText.options[pluginUidText.selectedIndex].value

**Comment by PabluskiNC** [comment]
I created a pull request ... simple change

**Comment by BlueAndi** [comment]
Thanks! Good finding.
