### ISSUE TITLE
Build Problems

### ISSUE THREAD

**Issue by Dlay2017** [BlueAndi/esp-rgb-led-matrix#162]
Hello,

i am totally lost when trying to build the project. 
Platformio runs into the following error:

`Resolving esp32doit-devkit-v1 dependencies...
Library Manager: Installing git+https://github.com/kosme/arduinoFFT#develop @ ~1.9.2
git version 2.44.0.windows.1
Cloning into 'C:\Users\XY\.platformio\.cache\tmp\pkg-installing-12ganwbg'...

PackageException: Package version 2.0.0+sha.909240f doesn't satisfy requirements ~1.9.2 based on PackageMetadata <type=library name=arduinoFFT version=2.0.0+sha.909240f spec={'owner': None, 'id': None, 'name': 'arduinoFFT', 'requirements': '~1.9.2', 'uri': 'git+https://github.com/kosme/arduinoFFT#develop'}`

**Comment by BlueAndi** [comment]
The arduinoFFT library was updated and it seems older versions are not available in the pio registry.
The development branch already considers this.

Can you use the development branch, until a bugfix version is released?
If not, please update locally like:
https://github.com/BlueAndi/esp-rgb-led-matrix/blob/e42928274bab166708bae63fe1f2c074ea8591c5/lib/AudioService/library.json#L17-L19
