### ISSUE TITLE
[Feature] Configurable "start of week" for DateTimePlugin lamps

### ISSUE THREAD

**Issue by ryannevell** [BlueAndi/esp-rgb-led-matrix#177]
The DateTimePlugin currently assumes that Monday is the first day of the week:

```
    /* tm_wday starts at sunday, first lamp indicates monday.*/
    uint8_t activeLamp = (0U < timeInfo.tm_wday) ? (timeInfo.tm_wday - 1U) : (DateTimePlugin::MAX_LAMPS - 1U);
```

In many locales, this is not the case, so having this be a configurable option for this plugin would be nice.

**Comment by BlueAndi** [comment]
I am currently on a business trip, I try to check it after I am back. Thx.
