### ISSUE TITLE
[Feature] Enable/disable plugin slots

### ISSUE THREAD

**Issue by Leeefy** [BlueAndi/esp-rgb-led-matrix#197]
To be able to turn on and off plugin slots instead of uninstalling a plugin, installing it later on in the day and having to configure the plugin again.
Example screenshot below (mockup) shows all plugin slots enabled besides slot 2, the openweather plugin, therefore the openweather plugin wont display on the matrix until enabled again.
![20241021_22h04m55s_grim](https://github.com/user-attachments/assets/5b619ee6-fcc2-496a-b916-f5392949a6c9)
also maybe have it compatible with rest api :)

**Comment by BlueAndi** [comment]
A first implementation is ready in the Development branch.
![image](https://github.com/user-attachments/assets/0aada0bb-5dfc-484e-b038-6eb02bf9a8f4)

The update on swagger for the REST API is open.

**Comment by BlueAndi** [comment]
REST API updated: https://app.swaggerhub.com/apis/BlueAndi/Pixelix/1.5.0
* https://app.swaggerhub.com/apis/BlueAndi/Pixelix/1.5.0#/Common/setSlot
* https://app.swaggerhub.com/apis/BlueAndi/Pixelix/1.5.0#/Common/getSlot
