### ISSUE TITLE
TEST_ASSERT_EQUAL_size_t 

### ISSUE THREAD

**Issue by romi06** [BlueAndi/esp-rgb-led-matrix#36]
{
	"resource": "/c:/Users/ROMI/OneDrive/Dokumenty/PlatformIO/Projects/RGB_ESP/rgb/test/TestMain.cpp",
	"owner": "C/C++",
	"code": "20",
	"severity": 8,
	"message": "identyfikator \"TEST_ASSERT_EQUAL_size_t\" jest niezdefiniowany",
	"source": "C/C++",
	"startLineNumber": 1695,
	"startColumn": 5,
	"endLineNumber": 1695,
	"endColumn": 29
}

**Comment by BlueAndi** [comment]
`TEST_ASSERT_EQUAL_size_t` is part of [Unity](https://github.com/ThrowTheSwitch/Unity/blob/master/src/unity.h). Did you use vscode + platformio?

**Comment by romi06** [comment]
So it's ok
Successful launch
Thanks for a good job :)
