### ISSUE TITLE
OpenWeather 

### ISSUE THREAD

**Issue by romi06** [BlueAndi/esp-rgb-led-matrix#37]
Is it possible to add OpenWeather as a Pugin

**Comment by BlueAndi** [comment]
Yes, its possible. Do you have one prepared?

**Comment by romi06** [comment]
I don't know much about coding.
That's why I ask
There are many examples such as "https://github.com/Qrome/marquee-scroller" 

Google translator

**Comment by 0ooYoo0** [comment]
TODO:
* ~~Icon handling depended on the weather icon id.~~
* ~~HTML plugin site.~~
* Perform some tests ;-)

**Comment by BlueAndi** [comment]
Looks good.
