### ISSUE TITLE
Consider OneWire for DHT in next HW version

### ISSUE THREAD

**Issue by BlueAndi** [BlueAndi/esp-rgb-led-matrix#40]
See #28
Currently the DHT is at pin 5. Note this is a strapping pin.
* Update schematic and layout.
* Update electronic descripton.
* Update BOM if necessary.

**Comment by flcu** [comment]
Just a small note - it seems that DHT11 does not speak "proper" OneWire but some simpler version of a OneWire protocol (if that matters..)

**Comment by BlueAndi** [comment]
@nischneider Did you consider this one?

**Comment by nischneider** [comment]
No, it is not implemented in v2.0

**Comment by BlueAndi** [comment]
@nischneider Can we close this issue, because its now part of HW v2.1 ?

**Comment by nischneider** [comment]
@BlueAndi yes we can close the issue
