### ISSUE TITLE
Custom plugin not detected

### ISSUE THREAD

**Issue by ReinVelt** [BlueAndi/esp-rgb-led-matrix#58]
I have created my own plugin following yours rules in plugins_dev.md . The files are compiled successfully and uploaded but the plugin is not working because it is not detected. PluginFactory.cpp detects all other plugins but not mine.

So here is my dumb question: How does pluginFactory get the list with available plugins?  Should i add something to a config file?

**Comment by BlueAndi** [comment]
Register the plugin in the InitState here:
https://github.com/BlueAndi/esp-rgb-led-matrix/blob/0c0b6bbee25cfb1dbdeda7b3249d0a51e9eba9ca/src/StateMachine/InitState.cpp#L379

I will add this to the documentation.

**Comment by ReinVelt** [comment]
Yes, it works. Thank you very much for your support.
