### ISSUE TITLE
Support of Distributed Display Protocol (DDP) protocol.

### ISSUE THREAD

**Issue by BlueAndi** [BlueAndi/esp-rgb-led-matrix#6]
http://openpixelcontrol.org/

**Comment by Nikey** [comment]
maybe better support DDP protocol, as it is used far more often in software (e.g. hyperion, ledfx...)
http://www.3waylabs.com/ddp/

**Comment by Nikey** [comment]
E1.31 is limited to around 510 LED's with 3 universes (if we want to reach 40 FPS), see here:
https://github.com/Aircoookie/WLED/wiki/E1.31-DMX

DDP is the far more capable one (around 30% more efficient), see the comparison here:
http://www.3waylabs.com/ddp/#Efficiency

When I have the choice, I would always pick DDP over E1.31 for the more fluent framerates.
When I use E1.31 on my 507 LED's-Strip, the last ~30 LED's don't refresh, so the real limit should be around 470 LED's
So If someone use 2 Matrix à 8x32 we would end up on this hard limit already (512 LED's).

Just my thoughts :)

**Comment by BlueAndi** [comment]
I did not analyse it yet, so interesting links. Will have a look in it. Thanks.

**Comment by BlueAndi** [comment]
https://github.com/smeighan/xLights/issues/3704

**Comment by BlueAndi** [comment]
https://github.com/BlueAndi/esp-rgb-led-matrix/blob/Development/doc/PLUGINS.md#ddpplugin
