### ISSUE TITLE
Login and password for the web interface

### ISSUE THREAD

**Issue by gubas** [BlueAndi/esp-rgb-led-matrix#68]
Hello !

I've been able to connect the pixelix with the good ssid and password, but when i try to connect to Web Interface, i have a pop up with login and password ?

![pixelix](https://user-images.githubusercontent.com/596670/150531838-e9bbbcde-f32a-4039-a4b0-62a03e31e4cb.png)
?

**Comment by gubas** [comment]
Sorry : i've found the answer in "src/Common/Settings.cpp" !

Perhaps it's a good idea to put it in the documentation ?

**Comment by BlueAndi** [comment]
Will be there in the next version, see previous commit.
