### ISSUE TITLE
Adapt REST API documentation

### ISSUE THREAD

**Issue by 0ooYoo0** [BlueAndi/esp-rgb-led-matrix#69]
Description of SensorPlugin and ThreeIconsPlugin should be added to Swagger.

**Comment by BlueAndi** [comment]
Add DateTimePlugin and SoundReactivePlugin to Swagger.

**Comment by BlueAndi** [comment]
REST API updated: https://app.swaggerhub.com/apis/BlueAndi/Pixelix/1.2.0
@0ooYoo0 please review.

**Comment by 0ooYoo0** [comment]
Done, no findings.
