### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by 0ooYoo0** [BlueAndi/esp-rgb-led-matrix#7]

**Comment by BlueAndi** [comment]
Waiting for [esp32 arduino](https://github.com/espressif/arduino-esp32) v2.0.0, as well as for [AsyncTCP](https://github.com/me-no-dev/AsyncTCP) with TLS support.

**Comment by BlueAndi** [comment]
AsyncTCP with TLS support is not available and therefore replaced by [AsyncTCPSock](https://github.com/yubox-node-org/AsyncTCPSock). [esp32 arduino v2.0.x](https://github.com/espressif/arduino-esp32) is available in the meantime, but currently not supported via PlatformIO (which will come, but unknown when).
