### ISSUE TITLE
Precompiled binarys for Wemos mini and ESP8266 

### ISSUE THREAD

**Issue by Rushmed** [BlueAndi/esp-rgb-led-matrix#70]
Hi.

Thanks for this project.
Is there a chance to offer precompiled .bin for ESP8266 and Wemos mini.

**Comment by BlueAndi** [comment]
Hi,
you are welcome. Supporting the esp8266 is currently not on the roadmap.
The esp8266 sw platform is community driven and the esp32 is driven by espressif. Unfortunately this causes differences, e.g. the preferences component only exists on esp32 side. All sw and hw differences must be analyzed to create a hardware abstraction layer concept. Unfortunately nothing which can be done in a short time in my opinion.

Conclusion for the moment: No, I can not promise.

**Comment by Rushmed** [comment]
Okay thaks!

**Comment by Rushmed** [comment]
Is there a prcompiled ESP32 version?

**Comment by BlueAndi** [comment]
No, not right now. We can open an issue and will plan it for the future. But there will be not only one esp32 binary, because we have to consider every esp32 variant and module, which means for consistency we have to provide several binaries.
And of course the binaries contain a fix LED topology.

**Comment by BlueAndi** [comment]
See #72
