### ISSUE TITLE
No Slots in Display

### ISSUE THREAD

**Issue by wendtc** [BlueAndi/esp-rgb-led-matrix#79]
Hi there ,
What can you do with the Display menu in the web interface?
I don't see any slots.
How can I install plugins in the web interface?
Christian

![2022-02-27 11_37_59-PIXELIX](https://user-images.githubusercontent.com/50050028/155878995-74024e37-f140-4643-abf6-c7fb71c04bb4.png)

**Comment by BlueAndi** [comment]
It seems your browser blocks the websocket communication. What browser do you use?

**Comment by wendtc** [comment]
Firefox

**Comment by BlueAndi** [comment]
Can you press F12 in the Firefox and have a look at the console which kind of errors there are?
Which version of Pixelix do you use?

**Comment by wendtc** [comment]
Version 5.0.1 
I have tested other Version its the same.
![image](https://user-images.githubusercontent.com/50050028/155879918-b0d34176-bf50-468c-a42e-05003e08f33a.jpeg)

**Comment by BlueAndi** [comment]
Can you show the "Konsole" tab?
I tested it with Edge, Chrome, Safari (IPhone) and Samsung Browser without any issue. Hmm...
Did you erase the whole flash before programming filesystem and firmware?

**Comment by wendtc** [comment]
I have testet with 3 new Chips - the same.
I don't know if that's a problem - the versioning doesn't work.
![2022-02-27 16_12_29-PIXELIX](https://user-images.githubusercontent.com/50050028/155888066-99500249-6322-48a3-b2b5-15f6da468deb.png)
where is the command to read sent?

**Comment by BlueAndi** [comment]
```~SW_VERSION~``` is replaced by the firmware with the correct version. Can you show me the log from the esp32 board?
How did you flash everything?

**Comment by wendtc** [comment]
Visual Studio Code
Download the source via zip.

**Comment by BlueAndi** [comment]
The log shows that the ```<ESP Async WebServer> 1.2.3``` is used, but that is invalid. This lead to the problem that all keywords surrounded with the tilde are not replaced and your browser throws the exception.

Did you change something in the platformio.ini?

**Comment by BlueAndi** [comment]
![image](https://user-images.githubusercontent.com/9699465/155892083-69209696-809d-4640-8a25-58a481efd791.png)

**Comment by BlueAndi** [comment]
Can you please upgrade your platformio? Because I see in your log other warning messages, which should not be there.
![image](https://user-images.githubusercontent.com/9699465/155892697-d90c46d0-9ab0-4573-a1f1-493deadfb1b0.png)

**Comment by wendtc** [comment]
Ich hab in der platform ini zeile 67 +68 auskommentiert und die 2 libs in das lib verzeichnis kopiert wegen der meldungen unten .

Ich habe jetzt noch mal eine blanke installation genommen.
Git gab ich auch noch mal installiert.

![image](https://user-images.githubusercontent.com/50050028/155893496-aced7e14-68ab-457c-acf3-09c589ef48e9.jpeg)

**Comment by BlueAndi** [comment]
Das Problem scheint platformio zu sein. Probiere folgendes:
1. Schliesse VSCode.
2. Lösche .platformio Verzeichnis in c:/Users/Christian bitte vollständig.
3. Öffne das Projekt in VSCode
4. Nun läuft die autom. Neuinstallation, bitte so lange warten, bis in der Konsole um einen Neustart von VSCode gebeten wird.
5. VSCode schliessen und nochmal Projekt öffnen.
6. Nun nochmal bauen und es sollte gehen.

**Comment by wendtc** [comment]
Ich teste und melde mich

**Comment by wendtc** [comment]
Super hat geklappt
Danke für die super Hilfe.
Daran hab ich gar nicht gedacht......
Christian

**Comment by BlueAndi** [comment]
Alles klar, gerne.
