### ISSUE TITLE
Replace SPIFFS by LittleFS

### ISSUE THREAD

**Issue by 0ooYoo0** [BlueAndi/esp-rgb-led-matrix#8]

**Comment by BlueAndi** [comment]
https://community.platformio.org/t/how-to-define-littlefs-partition-build-image-and-flash-it-on-esp32/11333
https://github.com/ARMmbed/littlefs
https://github.com/esp8266/Arduino/tree/master/libraries/LittleFS

**Comment by BlueAndi** [comment]
https://github.com/espressif/arduino-esp32/issues/3765#issuecomment-643975602
https://github.com/espressif/arduino-esp32/issues/3765#issuecomment-643996450
https://github.com/espressif/arduino-esp32/issues/3765#issuecomment-644011312

**Comment by BlueAndi** [comment]
https://github.com/me-no-dev/ESPAsyncWebServer/issues/792

**Comment by BlueAndi** [comment]
https://github.com/espressif/esp-idf/pull/5469

**Comment by BlueAndi** [comment]
https://github.com/lorol/LITTLEFS/tree/master/examples/LITTLEFS_PlatformIO

**Comment by BlueAndi** [comment]
LITTLEFS will be in ESP Arduino v2.0.0 available: https://github.com/espressif/arduino-esp32/pull/4096#issuecomment-720702901

**Comment by BlueAndi** [comment]
Open:
* File browser folder support
* LittleFS needs more space, check whether the meta data per file can be configured
