### ISSUE TITLE
Diffuser

### ISSUE THREAD

**Issue by viveksood97** [BlueAndi/esp-rgb-led-matrix#83]
What did you use to diffuse the light from LED's?

**Comment by BlueAndi** [comment]
Original (shown in the videos) it was a sandwich of
* car window tint film
* acrylic glas
* transparent white insert paper

In the meantime I replaced the acrylic glas and the transparent white insert paper with: https://www.thingiverse.com/thing:3884621

**Comment by viveksood97** [comment]
Can you provide the link for the tint you used?

**Comment by BlueAndi** [comment]
https://www.amazon.de/gp/product/B075NZN71N/ref=ppx_od_dt_b_asin_title_s00?ie=UTF8&psc=1
