### ISSUE TITLE
Thanks for helping me creating my new project.

### ISSUE THREAD

**Issue by andreacampanella** [BlueAndi/esp-rgb-led-matrix#84]
I just wanted to say hi and thanks.

I forked your project some times ago and I used to power it a 360 degree led sign with 8x96 leds, you can see a small video here:

https://photos.app.goo.gl/hqYgcTkVTKfsKUqF6

This was part of the Makerfair event held by the South London Makerspace, in London UK.

If you ever come by London, let me know, I own you a drink!

**Comment by BlueAndi** [comment]
You are welcome! Looks really nice. Unfortunately my  business trips ars in a different direction at the moment, but if I am near London I let you know. :-)

**Comment by andreacampanella** [comment]
Done.
