### ISSUE TITLE
HW v2.1

### ISSUE THREAD

**Issue by gabryelreyes** [BlueAndi/esp-rgb-led-matrix#91]
- [x] update I2S Pins on Feather (see Table: https://github.com/BlueAndi/esp-rgb-led-matrix/blob/Development/doc/boards/pixelix/v2.0/ELECTRONIC.md)
- [x] add One Wire (see #40)
- [x] add 3V3 and GND to I2S, I2C & One-Wire interface pins in a molex connector

**Comment by BlueAndi** [comment]
@gabryelreyes @nischneider Can we close this?
