### ISSUE TITLE
INMP441 Wiring

### ISSUE THREAD

**Issue by jimmyeao** [BlueAndi/esp-rgb-led-matrix#99]
Hi, what pins do I need to wire the INMP441 to? a quick google search shows a few variations of pin combinations

**Comment by jimmyeao** [comment]
I wired it like this:
![image](https://user-images.githubusercontent.com/5197831/201403412-4fbc9ac2-4c5d-4bc5-817c-b4254b9fbf8c.png)

But I get a very full display with a few of the columns jumping whether there is sound or not

**Comment by jimmyeao** [comment]
Perfect, thank you. Keep up the excellent work 😃

**Comment by BlueAndi** [comment]
Thanks, always good to hear its worthful.
